# Build configuration for Room-O-Matic Mobile
targets:
  $default:
    builders:
      json_serializable:
        generate_for:
          - lib/**/*.dart
      freezed:
        generate_for:
          - lib/**/*.dart
      riverpod_generator:
        generate_for:
          - lib/**/*.dart
