name: room_o_matic_mobile
description: Offline-first room measurement app with optional Room-O-Matic server integration
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # Functional Programming
  dartz: ^0.10.1

  # Data Classes & JSON
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # Database
  drift: ^2.14.1
  sqlite3_flutter_libs: ^0.5.18
  path_provider: ^2.1.1
  path: ^1.8.3

  # Security & Storage
  flutter_secure_storage: ^9.0.0
  local_auth: ^2.1.7
  crypto: ^3.0.3
  shared_preferences: ^2.2.2

  # Platform Channels (built into Flutter SDK)

  # Camera & AR
  camera: ^0.10.5+5

  # Audio for Sonar
  flutter_sound: ^9.2.13
  permission_handler: ^11.1.0

  # Export Functionality
  pdf: ^3.10.6
  share_plus: ^7.2.1

  # Network (Optional)
  http: ^1.1.2
  connectivity_plus: ^5.0.2

  # UI & Utilities
  go_router: ^12.1.3
  intl: ^0.18.1
  equatable: ^2.0.5
  uuid: ^4.2.1

  # Location Services
  geolocator: ^10.1.0

  # Image Processing
  image: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.5.4
  freezed: ^2.5.8
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9
  drift_dev: ^2.14.1

  # Testing
  mockito: ^5.4.4
  mocktail: ^1.0.2
  golden_toolkit: ^0.15.0

  # Linting
  flutter_lints: ^3.0.1
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/sounds/

  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700
