blank_issues_enabled: false
contact_links:
  - name: 💬 General Discussion
    url: https://github.com/greysquirr3l/copilot-goat/discussions
    about: Ask questions and discuss with the community
  - name: 🔒 Security Issues
    url: https://github.com/greysquirr3l/copilot-goat/security/advisories/new
    about: Report security vulnerabilities privately
  - name: 📚 Documentation
    url: https://github.com/greysquirr3l/copilot-goat#readme
