blank_issues_enabled: false
contact_links:
  - name: 💬 General Discussion
    url: https://github.com/sosh-ncampbell/room-o-matic-mobile/discussions
    about: Ask questions and discuss with the community
  - name: 🔒 Security Issues
    url: https://github.com/sosh-ncampbell/room-o-matic-mobile/security/advisories/new
    about: Report security vulnerabilities privately
  - name: 📚 Documentation
    url: https://github.com/sosh-ncampbell/room-o-matic-mobile#readme
    about: Browse project documentation and guides
